apiVersion: syftbox.openmined.org/v1alpha1
kind: Module
metadata:
  name: hello
  version: 0.1.0
spec:
  runner:
    kind: shell
    template: shell
    entrypoint: hello.sh
  outputs:
    - name: message
      type: File
      format: { kind: txt }
      path: hello.txt
