apiVersion: syftbox.openmined.org/v1alpha1
kind: Flow
metadata:
  name: module-folder-example
  version: 0.1.0
  description: Resolve a module from a folder using module_paths.
  authors:
    - you@example.org
spec:
  inputs:
    datasites:
      type: List[String]
      default: ["local@localhost"]

  datasites:
    all: inputs.datasites
    groups:
      local:
        include:
          - "{datasites[0]}"

  module_paths:
    - ./modules

  modules:
    hello:
      source:
        kind: local
        path: hello
      allow_dirty: true
      interface:
        outputs:
          - name: message
            type: File
            format: { kind: txt }

  steps:
    - id: hello
      uses: hello
      run:
        targets: local
      publish:
        message: outputs.message
