apiVersion: syftbox.openmined.org/v1alpha1
kind: Module
metadata:
  name: echoer
  version: 0.1.0
spec:
  runner:
    kind: shell
    template: shell
    entrypoint: echo.sh
  inputs:
    - name: text
      type: String
  outputs:
    - name: message
      type: File
      format: { kind: txt }
      path: message.txt
