apiVersion: syftbox.openmined.org/v1alpha1
kind: Module
metadata:
  name: collect
  version: 0.1.0
spec:
  runner:
    kind: shell
    template: shell
    entrypoint: collect.sh
  inputs:
    - name: shared_paths
      type: File
      format: { kind: txt }
    - name: wait_seconds
      type: String
  outputs:
    - name: combined
      type: File
      format: { kind: txt }
      path: combined.txt
